version: "3.8"
services:
  cluster-generator:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - WORKDIR=${WORKDIR}
    image: cluster-generator 
    container_name: cluster-generator
    ports:
      - ${PORT_RANGE}:${PORT_RANGE}
      - ${PORTAINER_PORT}:${PORTAINER_PORT}
      - ${HELM_DASHBOARD_PORT}:${HELM_DASHBOARD_PORT}
      - ${APISERVER_PORT}:${APISERVER_PORT}
    volumes:
      - .:${WORKDIR}
      - ./config:/root/.kube/
    #   - /var/run/docker.sock:/var/run/docker.sock
    #   - /usr/bin/docker:/usr/bin/docker
    tty: true
    privileged: true
    env_file:
      - .env
